# Generated by Django 4.1.7 on 2023-03-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_pages_book_slug_alter_book_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='votes',
            field=models.BigIntegerField(null=True),
        ),
    ]
