# Generated by Django 4.1.7 on 2023-03-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='affiliate_link',
            field=models.URLField(null=True, verbose_name='Amazon Affiliate Link'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.book'),
        ),
    ]
