# Generated by Django 4.1.7 on 2023-03-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book_affiliate_link_alter_quote_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='image',
            field=models.ImageField(null=True, upload_to='quotes/'),
        ),
    ]
