# Generated by Django 4.1.7 on 2023-03-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_book_description_book_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='external_link_text',
            field=models.CharField(max_length=255, null=True, verbose_name='External Link Text'),
        ),
    ]
