# Generated by Django 4.1.7 on 2023-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_book_source_or_credit_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='source_or_credit_text',
            field=models.CharField(choices=[('Source', 'Source'), ('Credit', 'Credit')], max_length=10, null=True, verbose_name='Source or Credit:'),
        ),
    ]
